### ISSUE TITLE
OrbitDB 1.0 Release

### ISSUE THREAD

**Issue by tabcat** [orbitdb/orbit-db#1008]
### Track the official release

- [x] [OrbitDB 1.0 BETA Release](https://github.com/orbitdb/orbit-db/issues/1002)
- [ ] [Draft Protocol Spec Merged](https://github.com/orbitdb/spec/issues/1)
- [ ] [Post OrbitDB 1.0 BETA Release Work](https://github.com/orbitdb/orbit-db/issues/1003)
- [ ] Security audit completed
- [ ] Protocol spec finalized
- [ ] Updated examples and other resources

ETA: EOY 2022

**Comment by tabcat** [comment]
About a month ago I was relieved from the maintainer role of OrbitDB. I'm no longer working on OrbitDB but plan on continuing the ideas under a new project.
The release tracker issues I created are not the best place to watch for a OrbitDB 1.0 and new feature set so I will close them.

Closes #1002
Closes #1003

**Comment by tabcat** [comment]
The official and original 1.0 tracker: [The Road to 1.0](https://github.com/orbitdb/orbit-db/issues/819)
